# Generated by Django 2.1.8 on 2019-05-04 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ingredient'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredient',
            new_name='Ingridient',
        ),
    ]
